# Generated by Django 2.2.2 on 2019-06-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='filmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('duraçao', models.CharField(max_length=100, verbose_name='Duraçao')),
                ('classificaçao', models.CharField(max_length=100, verbose_name='classificação')),
                ('fotos', models.ImageField(null=True, upload_to='filmes', verbose_name='Fotos')),
                ('genero', models.ManyToManyField(to='core.genero')),
            ],
        ),
    ]
