# Generated by Django 2.2.2 on 2019-06-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='genero',
            new_name='Generos',
        ),
    ]
